package es.daw.parallaxbot.common.dto

data class AlertStreamMessage(
    val schemaVersion: String,
    val alertId: Long,
    val userId: Long,
    val eventId: Long,
    val channel: String,
    val sendAtUtc: String,
    val idempotencyKey: String,
    val attempts: Int,
    val maxAttempts: Int,
    val artifactRequired: Boolean,
    val artifactId: Long? = null,
    val eventName: String? = null,
    val eventType: String? = null,
    val eventStatus: String? = null,
    val eventStartTimeUtc: String? = null,
    val eventEndTimeUtc: String? = null,
    val competitionName: String? = null,
    val venueName: String? = null,
    val venueTimezone: String? = null,
    val userTimezone: String? = null,
    val userLocale: String? = null,
    val userEmail: String? = null,
    val renderHash: String? = null,
    val discordDeliveryMode: String? = null,
    val discordUserId: String? = null,
    val discordChannelId: String? = null,
    val discordGuildId: String? = null
)