include "shared-data.conf"

ktor {
    deployment { port = 8084 }
    application { modules = [es.daw.parallaxbot.email.ApplicationKt.module ]}
}

parallaxbot {
    email {
        client {
            id = ${CLIENT_ID}
            secret = ${CLIENT_SECRET}
        }
        username = ${EMAIL}
        from = "ParallaxSports"

    }
}