include "shared-data.conf"

ktor {
    deployment { port = 8084 }
    application { modules = [es.daw.parallaxbot.email.ApplicationKt.module ]}
}

parallaxbot {
    email {
        username = ${EMAIL_USERNAME}
        from = "ParallaxSports"
    }
}