parallaxbot {
    email {
        client {
            id     = "replace-with-oauth-client-id"
            secret = "replace-with-oauth-client-secret"
        }
        username = "replace-with-gmail-address"
    }
}
