include "shared-data.conf"

ktor {
    deployment { port = 8083 }
    application { modules = [es.daw.parallaxbot.telegram.ApplicationKt.module ]}
}

parallaxbot {
    telegram {
            token = ${TELEGRAM_TOKEN}
        }
}