include "shared-data.conf"
include "application-secrets.conf"
include "application-secrets.local.conf"

ktor {
    deployment { port = 8083 }
    application { modules = [es.daw.parallaxbot.telegram.ApplicationKt.module] }
}
