ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ es.daw.parallaxdiscordbot.ApplicationKt.module ]
    }
}

# Discord Configuration
discord {
    token = ${DISCORD_TOKEN}
    server-id= "1472661815140815072"
    channels {
        main = "1472661816655220768"
        ping = "1472677343855251740"
    }
}

# Parallax API Configuration
api {
    base-url = "http://localhost:8081"
    key = ${API_KEY}
    endpoints {
        event = ${api.base-url}"/api/events"
        auth = ${api.base-url}"/api/auth/discord"
    }
}

