spring.application.name=TestSpringBot
discord.token=MTQ3MjY1MTMwMzUxMDYxMDE1NA.GeG0s4.NhId3lS5P4aJdBZokDThsYjGdsR18nea0pZJTw
discord.channel.id=1472661816655220768
discord.channel.ping.id=1472677343855251740
discord.server.id=1472661815140815072
telegram.username=TfgSpring_bot
telegram.channel=-1003442706219
telegram.token=8376455539:AAHA1XJU2LIV9gWY1FQ4JphUmFmADkCWZPk
catalog.base-url=http://localhost:8081
catalog.api-url=/api/eventos


