include "shared-data.conf"
include optional("shared-data.local.conf")
include "application-secrets.local.conf"

ktor {
    deployment { port = 8087 }
    application { modules = [es.daw.parallaxbot.playwright.ApplicationKt.module] }
}
