parallaxbot {
    api {
        base-url = "http://localhost:8081"
        key = ${API_KEY}
        endpoints {
                event = ${parallaxbot.api.base-url}"/api/events"
                auth = ${parallaxbot.api.base-url}"/api/auth"
        }
    }

    providers = [
        "8082"
    ]
}

