include "shared-secrets.conf"

parallaxbot {
    redis {
        url = "redis://localhost:6379"
        stream = "alerts-stream"
    }

    api {
        base-url = "http://localhost:8080"
        endpoints {
            event = ${parallaxbot.api.base-url}"/api/events"
            auth  = ${parallaxbot.api.base-url}"/api/auth"
        }
    }
}

