package es.daw.parallaxbot.discord.utils

import es.daw.parallaxbot.common.dto.AlertStreamMessage
import net.dv8tion.jda.api.EmbedBuilder
import net.dv8tion.jda.api.entities.MessageEmbed
import java.awt.Color
import java.time.Instant

/**
 * Builds Discord embed payloads for command and alert flows.
 */
object EmbedFactory {

    private val ICON = null
    private val DEFAULT_COLOR = Color.decode("#2F3126")

    /**
     * Creates the shared base embed shape used by command responses.
     *
     * @return mutable embed builder with shared footer and timestamp.
     */
    private fun base(): EmbedBuilder {
        return EmbedBuilder()
            .setTimestamp(Instant.now())
            .setFooter("ParallaxBot + Gaming Alerts", ICON)
    }

    /**
     * Creates a league schedule embed shell for the selected event type.
     *
     * @param type league or tournament identifier.
     * @return embed builder preconfigured with title, accent color, and thumbnail.
     */
    fun leagueSchedule(type: String): EmbedBuilder {
        val color = when (type.uppercase()) {
            "LEC" -> Color.ORANGE
            "LVP" -> Color.BLUE
            "WORLDS" -> Color.YELLOW
            else -> Color.CYAN
        }

        return base()
            .setTitle("$type Schedule")
            .setColor(color)
            .setThumbnail("https://lol-logo-url.png")
    }

    /**
     * Creates the account-linking embed shown during Discord login flow.
     *
     * @param userName Discord display name.
     * @param avatarUrl optional user avatar for author metadata.
     * @return embed builder to append auth link details.
     */
    fun userAuth(userName: String, avatarUrl: String?): EmbedBuilder {
        return base()
            .setTitle("User Authentication")
            .setAuthor(userName, null, avatarUrl)
            .setColor(Color.GREEN)
            .setDescription("Please follow the link below to link your account")
    }

    /**
     * Creates a standard error embed for user-facing command failures.
     *
     * @param message safe error context intended for user visibility.
     * @return embed builder with error visual styling.
     */
    fun error(message: String): EmbedBuilder {
        return base()
            .setTitle("Error")
            .setDescription(message)
            .setColor(Color.RED)
    }

    /**
     * Creates the final event alert embed dispatched by worker consumers.
     *
     * @param message alert event data used for title and schedule metadata.
     * @param imageUrl optional image URL generated by Playwright/Cloudinary flow.
     * @return immutable Discord embed ready for provider delivery.
     */
    fun createEventEmbed(message: AlertStreamMessage, imageUrl: String?): MessageEmbed {
        val builder = EmbedBuilder()
            .setTitle("🏁 ${message.eventName}")
            .setDescription("El evento está por comenzar")
            .setColor(Color.RED)
            .setTimestamp(Instant.parse(message.sendAtUtc))

        if (imageUrl != null) {
            builder.setImage(imageUrl)
        }

        return builder.build()
    }
}