include "shared-data.conf"

ktor {
    deployment { port = 8082 }
    application { modules = [es.daw.parallaxbot.discord.ApplicationKt.module ]}
}

parallaxbot {
    discord {
        token = ${DISCORD_TOKEN}
        server-id= "1472661815140815072"
        channels {
            main = "1472661816655220768"
                    ping = "1472677343855251740"
        }
    }
}
