include "shared-data.conf"
include "shared-data.local.conf"
include "application-secrets.conf"
include "application-secrets.local.conf"

ktor {
    deployment { port = 8082 }
    application { modules = [es.daw.parallaxbot.discord.ApplicationKt.module] }
}

parallaxbot {
    discord {
    }
}
